#!/bin/python
import sqlite3, sys, errno, os, database, visualize, utils

confFolder = "~/.hiwi/"
databaseFile = "database.db"

def help():
    print("Usage: hiwi ( [start | stop <work notes> | list <month> | delete <id number> | help] )")
utils.help = help

def start(db, argv):
    utils.checkNumberOfArgs(argv, 0)
    if db.startTicket() == False:
        utils.panic("There already is an open work ticket.")
    visualize.openTickets(db)

def stop(db, argv):
    notes = " ".join(argv[1:])
    if db.stopTicket(notes) == False:
        utils.panic("There is no open work ticket.")
    else:
        visualize.closedTickets(db)

def delete(db, argv):
    utils.checkNumberOfArgs(argv, 1)
    utils.checkIsInt(argv[1])
    id = argv[1]

    if visualize.ticket(db, id) == False:
        utils.panic("There is no ticket #{}.".format(id))

    if utils.question("Really delete above ticket #{}?".format(id), "no"):
        db.deleteEntry(id)
        print("Deleted ticket #{}.".format(id))
    else:
        print("Aborted.")

def list(db, argv):
    utils.checkNumberOfArgs(argv, 1)
    utils.checkIsInt(argv[1])
    if visualize.summary(db, argv[1]) == False:
        print("There are no work tickets for {:02}.".format(int(argv[1])))

def run(db, argv):
    action = argv[0]
    funcs = {
            "start": start,
            "stop": stop,
            "delete": delete,
            "list": list,
            }
    if action in funcs:
        funcs[action](db, argv)
    else:
        utils.panic("Unknown command: {}".format(action))

def main(argv):
    confFolderExpanded = os.path.expanduser(confFolder)
    try:
        os.makedirs(confFolderExpanded)
    except OSError as ex:
            if ex.errno == errno.EEXIST and os.path.isdir(confFolderExpanded):
                pass
            else:
                raise
    work = database.Work(confFolderExpanded + databaseFile, "WorkingTime")
    if len(argv) > 0:
        run(work, argv)
    else:
        if visualize.openTickets(work) == False:
            visualize.closedTickets(work)

if __name__ == "__main__":
    main(sys.argv[1:])
