#!/bin/python
import sqlite3, sys, database, visualize, utils, action

confFolder = "~/.worklog/"
databaseFile = "database.db"

def help(longDescription = False):
    print("Usage: \t\033[1mworklog <name> [optional command]\033[0m")
    print()
    print("Commands:")
    print("\tstart")
    print("\tstop (<work notes>)")
    print("\tlog | log <month>")
    print("\tsum <month>")
    print("\tadd <date> <start time> <stop time> <work notes>")
    print("\tdelete <id number>")
    print("\thelp")

    if longDescription:
        print()
        print("Detailed commands:")
        print("  \033[1mstart\033[0m")
        print("      Starts the working ticket.")
        print("  \033[1mstop (<work notes>)\033[0m")
        print("      Stops the working ticket.")
        print("      Use <work notes> to summarize the work (optional).")
        print("  \033[1mlog | log <month>\033[0m")
        print("      Show a detailed list for <month> (format: MM/YYYY).")
        print("      Omitting <month> prints every record there is.")
        print("  \033[1msum <month>\033[0m")
        print("      Show a work summary for <month> (format: MM/YYYY).")
        print("  \033[1madd <date> <start time> <stop time> <work notes>\033[0m")
        print("      Create a work record with the given arguments.")
        print("      Formatting:")
        print("        <date>: DD.MM.YYYY")
        print("        <start time> <stop time>: HH:MM")
        print("  \033[1mdelete <id number>\033[0m")
        print("      Delete the work record with the given <id number>.")
        print("  \033[1mhelp\033[0m")
        print("      Print this.")
utils.help = help

def run(db, argv):
    cmd = argv[1]
    funcs = {
            "start": action.start,
            "stop": action.stop,
            "log": action.log,
            "sum": action.sum,
            "add": action.add,
            "delete": action.delete,
            }
    if cmd in funcs:
        funcs[cmd](db, argv[2:])
    else:
        utils.panic("Unknown command: {}".format(cmd))

def main(argv):
    if len(argv) == 0:
        help()
    elif argv[0] == "help" or argv[0] == "-h":
        help(longDescription = True)
    else:
        db = sqlite3.connect(utils.prepareFolder(confFolder) + databaseFile)
        work = database.WorkTable(db.cursor(), argv[0])
        if len(argv) == 1:
            if visualize.openTickets(work) == False:
                visualize.closedTickets(work, 8)
        elif len(argv) > 1:
            run(work, argv)  # TODO: Try/catch for argument errors.
        db.commit()
        db.close()

if __name__ == "__main__":
    main(sys.argv[1:])
